"""Regenerates docs/models and the model tables in the READMEs from this Mac's CoreTypes.bundle.

macOS only. device-icons exports the icons of the pictured model identifiers into a temporary directory; docs/models
keeps its `icons/` and `sidebar/`, quantised with pngquant, and each README gets the export's table spliced in
between `<!-- docs-models -->` and `<!-- /docs-models -->`, followed by a comment naming the call that made it.
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

DEVICE_ICONS = ["uvx", "--from", "git+https://github.com/bkahlert/device-icons@v0.2.0", "device-icons"]
PNGQUANT = ["pngquant", "--force", "--skip-if-larger", "--strip", "--ext", ".png"]
PNGQUANT_SKIPPED = 98
START, END = "<!-- docs-models -->", "<!-- /docs-models -->"


@dataclass(frozen=True)
class Table:
    """A model table in a README: the model identifiers it pictures and how the export's table is fitted to the file."""

    readme: str
    models: tuple[str, ...]
    prefix: str
    """What `src=` paths get in front of `icons/` and `sidebar/`, relative to the README."""
    width: int | None = None
    """Every image this wide; None keeps device-icons' 128 px icons and 32 px sidebar icons."""


TABLES = (
    Table(
        "devices/README.md",
        ("AirPort4", "AirPort5", "AirPort6", "AirPort7,120", "Macmini8,1", "Macmini9,1", "MacPro6,1", "MacPro5,1",
         "MacPro7,1@ECOLOR=225,225,223", "MacPro7,1@ECOLOR=226,226,224", "Xserve3,1"),
        "../docs/models/",
    ),
    Table("README.md", ("AirPort4", "AirPort7,120", "MacPro7,1@ECOLOR=226,226,224"), "docs/models/", width=64),
)


def export_command(models: tuple[str, ...]) -> list[str]:
    """Return the device-icons call that exports the given model identifiers as a horizontal table."""
    return [*DEVICE_ICONS, "icons", "export", "--horizontal", "--no-open", *(arg for model in models for arg in ("--model", model))]


def table(export_readme: str, prefix: str, width: int | None = None) -> str:
    """Return the table of an export's README.md, `src=` paths prefixed with prefix and, given a width, every image that wide."""
    body = export_readme.split("\n", 2)[2].replace('src="', f'src="{prefix}')
    if width is not None:
        body = re.sub(r'width="\d+"', f'width="{width}"', body)
    return body.strip("\n") + "\n"


def comment(spec: Table) -> str:
    """Return the HTML comment naming the call and the post-processing the table above it was made with."""
    call = " \\\n".join(shell_lines(export_command(spec.models)))
    fitted = f"the image paths prefixed with {spec.prefix}" + (f" and every width set to {spec.width}" if spec.width is not None else "")
    return (
        "<!--\n"
        "The table above is generated by `make docs-models`, which runs\n"
        "\n"
        f"{call}\n"
        "\n"
        f"then keeps the export's icons/ and sidebar/ as docs/models/, quantised with pngquant, and splices in its table with\n"
        f"{fitted}.\n"
        "-->\n"
    )


def shell_lines(command: list[str], width: int = 98) -> list[str]:
    """Return the export command as indented lines: the options on the first, `--model` pairs packed onto the rest."""
    first = command.index("--model")
    lines = ["    " + " ".join(command[:first])]
    for pair in (" ".join(command[i : i + 2]) for i in range(first, len(command), 2)):
        if len(lines[-1]) + 1 + len(pair) > width:
            lines.append("      " + pair)
        else:
            lines[-1] += " " + pair
    return lines


def block(spec: Table, export_readme: str) -> str:
    """Return what goes between the markers of a README: the fitted table, a blank line, and the comment."""
    return f"{table(export_readme, spec.prefix, spec.width)}\n{comment(spec)}"


def splice(text: str, block: str) -> str:
    """Return text with what lies between the docs-models markers replaced by block.

    Raises ValueError when a marker is missing or the end marker comes first.
    """
    start, end = text.find(START), text.find(END)
    if start < 0 or end < start:
        raise ValueError(f"no {START} ... {END} block")
    start += len(START)
    return f"{text[:start]}\n{block}{text[end:]}"


def install(root: Path, exports: list[tuple[Table, Path]]) -> None:
    """Replace root/docs/models with the icons of all exports and splice every README's table from its export."""
    models = root / "docs" / "models"
    shutil.rmtree(models, ignore_errors=True)
    for _, export in exports:
        for kind in ("icons", "sidebar"):
            shutil.copytree(export / kind, models / kind, dirs_exist_ok=True)
    for spec, export in exports:
        readme = root / spec.readme
        readme.write_text(splice(readme.read_text(), block(spec, (export / "README.md").read_text())))


def quantise(pngs: list[Path]) -> None:
    """Run pngquant over the given PNGs in place; one that would grow is kept as is."""
    for png in pngs:
        result = subprocess.run([*PNGQUANT, str(png)])
        if result.returncode not in (0, PNGQUANT_SKIPPED):
            raise SystemExit(f"pngquant failed on {png} with exit code {result.returncode}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/models and the model tables in the READMEs with device-icons.")
    parser.parse_args(argv)
    if sys.platform != "darwin":
        print("docs-models is macOS only", file=sys.stderr)
        return 2
    if not shutil.which("pngquant"):
        print("needs pngquant: brew install pngquant", file=sys.stderr)
        return 2
    root = Path.cwd()
    with tempfile.TemporaryDirectory() as tmp:
        exports = []
        for index, spec in enumerate(TABLES):
            out = Path(tmp) / str(index)
            if subprocess.run([*export_command(spec.models), str(out)]).returncode:
                raise SystemExit(f"device-icons icons export failed for {spec.readme}")
            exports.append((spec, out))
        install(root, exports)
    quantise(sorted((root / "docs" / "models").rglob("*.png")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
